# Generated by Django 5.0.1 on 2024-12-02 02:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorekbUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Manual Corekb Upload', max_length=100)),
                ('file', models.FileField(upload_to='corekb/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_inserted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_input_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('scenario_input', models.TextField()),
                ('scenario_element_advice', models.TextField(blank=True, null=True)),
                ('scenario_input_summary', models.TextField(blank=True, null=True)),
                ('scenario_factor_advice', models.TextField(blank=True, null=True)),
                ('scenario_solution_input', models.TextField(blank=True, null=True)),
                ('scenario_solution_advice', models.TextField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
