# Generated by Django 5.0.1 on 2024-12-07 02:12

import solutions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corekbupload',
            name='file',
            field=models.FileField(storage=solutions.models.CorekbDocumentStorage(), upload_to=solutions.models.corekb_document_path),
        ),
    ]
