# Generated by Django 5.0.1 on 2024-12-11 13:27

import solutions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_corekbupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='scenario_input_summary',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_element_advice',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_factor_advice',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_input',
            field=models.TextField(help_text='Input between 50 and 300 words.', validators=[solutions.models.validate_word_count]),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_solution_advice',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_solution_input',
            field=models.TextField(blank=True, help_text='Input between 50 and 300 words.', null=True, validators=[solutions.models.validate_word_count]),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='user_feedback',
            field=models.TextField(blank=True, help_text='Input between 50 and 300 words.', null=True, validators=[solutions.models.validate_word_count]),
        ),
    ]
