# Generated by Django 5.0.1 on 2025-01-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_remove_scenario_scenario_input_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='feedback_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenario_form_submission_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='solution_form_submission_count',
            field=models.IntegerField(default=0),
        ),
    ]
