# Generated by Django 5.0.1 on 2025-01-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_scenario_feedback_submitted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='feedback_submitted',
            new_name='experience_submitted',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='user_feedback',
            new_name='user_experience',
        ),
    ]
