# Generated by Django 5.0.1 on 2025-03-19 08:36

import solutions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_rename_feedback_submitted_scenario_experience_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='scenario_input',
            field=models.TextField(help_text='Input between 50 and 600 words.', validators=[solutions.models.validate_word_count]),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_solution_input',
            field=models.TextField(blank=True, help_text='Input between 50 and 600 words.', null=True, validators=[solutions.models.validate_word_count]),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='user_experience',
            field=models.TextField(blank=True, help_text='Input between 50 and 600 words.', null=True, validators=[solutions.models.validate_word_count]),
        ),
    ]
