# Generated by Django 5.0.1 on 2025-01-06 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userfreetrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfreetrial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfreetrial',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
