# Generated by Django 5.0.1 on 2025-01-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userfreetrial_created_at_userfreetrial_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfreetrial',
            name='scenario_creation_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
