# Generated by Django 5.0.1 on 2025-03-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userfreetrial_scenario_creation_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfreetrial',
            name='first_usage_reported',
            field=models.BooleanField(default=False),
        ),
    ]
