# Generated by Django 5.0.1 on 2024-12-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserviceprofile',
            name='scenarios_remaining',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
