# Generated by Django 5.0.1 on 2025-01-04 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_userserviceprofile_scenarios_remaining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='userserviceprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='start_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='scenarios_remaining',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='first_usage_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('past_due', 'Past Due')], default='Incomplete', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserServiceProfile',
        ),
    ]
