# Generated by Django 5.0.1 on 2025-01-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_usersubscription_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('past_due', 'Past Due')], default='active', max_length=50),
        ),
    ]
