# Generated by Django 5.0.1 on 2025-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_usersubscription_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], max_length=50, null=True),
        ),
    ]
