# Generated by Django 5.0.1 on 2025-03-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_usersubscription_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid')], max_length=50, null=True),
        ),
    ]
